version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 girlfriend_gpt.wsgi:application
    volumes:
      - .:/girlfirend_gpt
    ports:
      - "8000:8000"